# Generated by Django 6.0.2 on 2026-02-05 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarangHabisPakai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('stok', models.IntegerField()),
                ('satuan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=50)),
                ('judul', models.CharField(max_length=200)),
                ('pengarang', models.CharField(max_length=200)),
                ('jumlah', models.IntegerField()),
                ('tahun', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gedung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=200)),
                ('lokasi', models.CharField(max_length=200)),
                ('luas', models.FloatField()),
                ('kondisi', models.CharField(max_length=100)),
                ('tahun_perolehan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=200)),
                ('panjang', models.FloatField()),
                ('lokasi', models.CharField(max_length=200)),
                ('kondisi', models.CharField(max_length=100)),
                ('tahun_perolehan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PeralatanMesin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=200)),
                ('jumlah', models.IntegerField()),
                ('kondisi', models.CharField(max_length=100)),
                ('tahun_perolehan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tanah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=200)),
                ('luas', models.FloatField()),
                ('lokasi', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('tahun_perolehan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peminjam', models.CharField(max_length=200)),
                ('jumlah_pinjam', models.IntegerField()),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('dipinjam', 'Dipinjam'), ('kembali', 'Kembali')], default='dipinjam', max_length=20)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarpras.peralatanmesin')),
            ],
        ),
    ]
