# Generated by Django 6.0.2 on 2026-02-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarpras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peralatanmesin',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='peralatan/'),
        ),
    ]
