# Generated by Django 6.0.2 on 2026-02-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarpras', '0002_peralatanmesin_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='buku/'),
        ),
    ]
