# Generated by Django 6.0.2 on 2026-02-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarpras', '0003_buku_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='kondisi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
