# Generated by Django 6.0.2 on 2026-02-06 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sarpras', '0004_buku_kondisi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='tahun',
            new_name='tahun_terbit',
        ),
    ]
