# Generated by Django 6.0.2 on 2026-02-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarpras', '0005_rename_tahun_buku_tahun_terbit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='judul',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buku',
            name='kondisi',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='buku',
            name='pengarang',
            field=models.CharField(max_length=255),
        ),
    ]
