# Generated by Django 6.0.2 on 2026-02-09 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sarpras', '0006_alter_buku_judul_alter_buku_kondisi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarangHabisPakai',
        ),
    ]
