# Generated by Django 6.0.2 on 2026-02-09 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarpras', '0007_delete_baranghabispakai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='sarpras.peralatanmesin'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='jumlah_pinjam',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='peralatanmesin',
            name='jumlah',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peralatanmesin',
            name='kode_barang',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='peralatanmesin',
            name='tahun_perolehan',
            field=models.PositiveIntegerField(),
        ),
    ]
