# Generated by Django 6.0.2 on 2026-02-10 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarpras', '0008_alter_peminjaman_barang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangHabisPakai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=50, unique=True)),
                ('nama_barang', models.CharField(max_length=200)),
                ('satuan', models.CharField(default='Unit', max_length=50)),
                ('stok', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BarangHabisPakaiKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('pengguna', models.CharField(max_length=200)),
                ('keperluan', models.CharField(max_length=200)),
                ('keterangan', models.TextField(blank=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keluar', to='sarpras.baranghabispakai')),
            ],
        ),
        migrations.CreateModel(
            name='BarangHabisPakaiMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('sumber', models.CharField(max_length=200)),
                ('keterangan', models.TextField(blank=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masuk', to='sarpras.baranghabispakai')),
            ],
        ),
    ]
