# Generated by Django 6.0.2 on 2026-02-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarpras', '0009_baranghabispakai_baranghabispakaikeluar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kode', models.CharField(max_length=50)),
                ('penanggung_jawab', models.CharField(blank=True, max_length=200, null=True)),
                ('gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruangan', to='sarpras.gedung')),
            ],
        ),
    ]
