# Generated by Django 6.0.2 on 2026-02-11 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarpras', '0010_ruangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='peralatanmesin',
            name='ruangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peralatan', to='sarpras.ruangan'),
        ),
    ]
